#!/usr/bin/env python3
from pathlib import Path
import re

import imageio.v2 as imageio
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "logo" / "DeskPet-mp4"
OUT = ROOT / "firmware" / "src" / "deskpet_animations.h"

SIZE = 320
COLORS = 64
FRAME_INDICES = [0, 12, 24, 34, 35, 46, 60, 70]
FRAME_MS = 125


def symbol_for(path: Path) -> str:
    stem = re.sub(r"^\d+-", "", path.stem)
    return re.sub(r"[^a-z0-9]+", "_", stem.lower()).strip("_")


def enum_for(sym: str) -> str:
    return "DESKPET_ANIM_" + sym.upper()


def rgb565(rgb):
    r, g, b = rgb
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def rle_encode(data: bytes) -> bytes:
    out = bytearray()
    i = 0
    while i < len(data):
        v = data[i]
        run = 1
        while i + run < len(data) and data[i + run] == v and run < 255:
            run += 1
        out.append(run)
        out.append(v)
        i += run
    return bytes(out)


def write_array(f, c_type, name, values, per_line=16):
    f.write(f"static const {c_type} {name}[] = {{\n")
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        if c_type == "uint8_t":
            rendered = ", ".join(f"0x{x:02x}" for x in chunk)
        elif c_type == "uint16_t":
            rendered = ", ".join(f"0x{x:04x}" for x in chunk)
        else:
            rendered = ", ".join(str(x) for x in chunk)
        f.write(f"    {rendered},\n")
    f.write("};\n\n")


def load_frames(path: Path):
    reader = imageio.get_reader(str(path), "ffmpeg")
    frames = []
    try:
        for idx in FRAME_INDICES:
            img = Image.fromarray(reader.get_data(idx)).convert("RGB")
            frames.append(img.resize((SIZE, SIZE), Image.Resampling.LANCZOS))
    finally:
        reader.close()
    return frames


def quantize_animation(frames):
    sheet = Image.new("RGB", (SIZE * len(frames), SIZE))
    for idx, img in enumerate(frames):
        sheet.paste(img, (idx * SIZE, 0))
    palette_image = sheet.quantize(colors=COLORS, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    raw_palette = palette_image.getpalette()[:COLORS * 3]
    palette = [
        rgb565(raw_palette[i:i + 3])
        for i in range(0, len(raw_palette), 3)
    ]
    while len(palette) < COLORS:
        palette.append(0)

    encoded_frames = []
    for img in frames:
        q = img.quantize(palette=palette_image, dither=Image.Dither.NONE)
        encoded_frames.append(rle_encode(q.tobytes()))
    return palette, encoded_frames


def main():
    paths = sorted(SRC_DIR.glob("*.mp4"))
    if not paths:
        raise SystemExit(f"No mp4 files found in {SRC_DIR}")

    assets = []
    for path in paths:
        sym = symbol_for(path)
        frames = load_frames(path)
        palette, encoded_frames = quantize_animation(frames)
        offsets = []
        sizes = []
        blob = bytearray()
        for frame in encoded_frames:
            offsets.append(len(blob))
            sizes.append(len(frame))
            blob.extend(frame)
        assets.append({
            "path": path,
            "sym": sym,
            "enum": enum_for(sym),
            "name": sym.replace("_", " "),
            "palette": palette,
            "offsets": offsets,
            "sizes": sizes,
            "blob": bytes(blob),
        })

    with OUT.open("w") as f:
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write("// Generated by tools/generate_deskpet_animations.py from logo/DeskPet-mp4/*.mp4.\n")
        f.write("// 64-color indexed frames, RLE encoded as (run, palette_index) byte pairs.\n")
        f.write(f"#define DESKPET_ANIM_W {SIZE}\n")
        f.write(f"#define DESKPET_ANIM_H {SIZE}\n")
        f.write(f"#define DESKPET_ANIM_PALETTE_SIZE {COLORS}\n")
        f.write(f"#define DESKPET_ANIM_DEFAULT_FRAME_MS {FRAME_MS}\n\n")

        f.write("enum deskpet_anim_id_t {\n")
        for asset in assets:
            f.write(f"    {asset['enum']},\n")
        f.write("    DESKPET_ANIM_COUNT,\n")
        f.write("};\n\n")

        f.write("typedef struct {\n")
        f.write("    const char* name;\n")
        f.write("    uint8_t frame_count;\n")
        f.write("    const uint16_t* palette;\n")
        f.write("    const uint16_t* holds;\n")
        f.write("    const uint32_t* offsets;\n")
        f.write("    const uint32_t* sizes;\n")
        f.write("    const uint8_t* data;\n")
        f.write("} deskpet_anim_asset_t;\n\n")

        for asset in assets:
            sym = asset["sym"]
            f.write(f"// {asset['path'].name}\n")
            write_array(f, "uint16_t", f"deskpet_{sym}_palette", asset["palette"], per_line=8)
            write_array(f, "uint16_t", f"deskpet_{sym}_holds", [FRAME_MS] * len(FRAME_INDICES), per_line=8)
            write_array(f, "uint32_t", f"deskpet_{sym}_offsets", asset["offsets"], per_line=8)
            write_array(f, "uint32_t", f"deskpet_{sym}_sizes", asset["sizes"], per_line=8)
            write_array(f, "uint8_t", f"deskpet_{sym}_data", asset["blob"], per_line=18)

        f.write("static const deskpet_anim_asset_t deskpet_anim_assets[DESKPET_ANIM_COUNT] = {\n")
        for asset in assets:
            sym = asset["sym"]
            f.write(
                f'    {{"{asset["name"]}", {len(FRAME_INDICES)}, '
                f"deskpet_{sym}_palette, deskpet_{sym}_holds, "
                f"deskpet_{sym}_offsets, deskpet_{sym}_sizes, deskpet_{sym}_data}},\n"
            )
        f.write("};\n")

    total = sum(len(a["blob"]) + COLORS * 2 + len(FRAME_INDICES) * 10 for a in assets)
    print(f"Wrote {OUT}")
    print(f"{len(assets)} animations, approx binary payload {total} bytes")


if __name__ == "__main__":
    main()
